### PR TITLE
[GH-#92] Making the code less repeated, fixing minor code errors.

### LINKED ISSUE #92: Fixing inconsistencies of the code
There are some inconsistencies in the code that I've found yesterday, and few possible refactoring opportunites in the elixir_wallet module. Some of the code there is repeated, so there should be a way to avoid this.

### PR DESCRIPTION
**Pull request by gspasov**
Fixed the repeated code in the create_wallet() and import_wallet() functions and in the get_private_key() and get_public_key() functions in the Wallet module. Fixed some documentation, added needed specifications for some functions.

resolves #92

### CODE REVIEW

File: lib/aewallet/elixir_wallet.ex [hunk 1]
```diff
@@ -44,24 +45,22 @@ defmodule Aewallet.Wallet do
 
   ## Examples
       iex> Wallet.create_wallet(password, path)
-      Use the following phrase as additional authentication
-      when accessing you wallet:
+      {:ok, "whisper edit clump violin blame few ancient casual
```
Comment (thepiwo) [inline lib/aewallet/elixir_wallet.ex]: shouldn't this be the encryption password?

File: lib/aewallet/elixir_wallet.ex [hunk 2]
```diff
@@ -199,33 +186,25 @@ defmodule Aewallet.Wallet do
...
 
-      {:ok, mnemonic, wallet_type, pass_phrase} ->
-        private_key =
-          mnemonic
-          |> KeyPair.generate_seed(pass_phrase)
-          |> KeyPair.generate_master_key(network, type: wallet_type)
-        {:ok, private_key.key}
+    {:ok, _, wallet_type, _} = Wallet.load_wallet_file(file_path, password)
+
+    case Aewallet.Wallet.get_public_key(file_path, password) do
```
Comment (thepiwo) [inline lib/aewallet/elixir_wallet.ex]: use the alias for `Wallet`

File: lib/aewallet/key_pair.ex [hunk 3]
```diff
@@ -236,7 +241,7 @@ defmodule Aewallet.KeyPair do
   @spec derive_key(privkey(), integer()) :: privkey()
   defp derive_key(%PrivKey{} = key, index) when index > -1 and index <= @mersenne_prime do
     # Normal derivation
-    compressed_pub_key = generate_pub_key(key, :compressed)
+    compressed_pub_key = Aewallet.KeyPair.generate_pub_key(key.key, :compressed)
```
Comment (thepiwo) [inline lib/aewallet/key_pair.ex]: use an alias

File: lib/aewallet/elixir_wallet.ex [hunk 4]
```diff
@@ -274,23 +255,29 @@ defmodule Aewallet.Wallet do
...
         :nil ->
-          {:ok, mnemonic, wallet_type}
+          {:ok, mnemonic, wallet_type, ""}
+
         pass_phrase ->
           {:ok, mnemonic, wallet_type, pass_phrase}
+
         _ ->
-          {:ok, mnemonic, wallet_type}
+          {:ok, mnemonic, wallet_type, ""}
```
Comment (thepiwo) [inline lib/aewallet/elixir_wallet.ex]: what is the `""`?

Comment (gspasov) [reply lib/aewallet/elixir_wallet.ex]: @thepiwo I just pass en empty string if there is no pass_phrase. If it's not that understandable maybe I could make a variable called like no_pass_phrase = "" and use it instead

File: lib/aewallet/elixir_wallet.ex (hunk 1 above)
Comment (gspasov) [reply lib/aewallet/elixir_wallet.ex]: @thepiwo I don't return the password for encryption that the user has given me, nor I return the pass_phrase if entered. In my opinion the user can remeber his own passwords :)

Comment (thepiwo) [reply lib/aewallet/elixir_wallet.ex]: yes exactly, but why do you use a mnemonic instead of some password as example?

File: lib/aewallet/elixir_wallet.ex (hunk 4 above)
Comment (thepiwo) [reply lib/aewallet/elixir_wallet.ex]: thanks for the explanation, you can do it like this

File: lib/aewallet/elixir_wallet.ex (hunk 1 above)
Comment (gspasov) [reply lib/aewallet/elixir_wallet.ex]: The idea is to use this mnemonic later to create the seed, and the whole wallet from it. If you mean why do I type the whole mnemonic in the example, I did it for clarity, I could replace it for something like mnemonic_code_words

Comment (thepiwo) [reply lib/aewallet/elixir_wallet.ex]: `create_wallet` takes a password to encrypt the mnemonic_phrase it generates in L62, as far as I understand. I want the example, not to use a mnemonic as password, as it confuses what the method actually does.

Comment (gspasov) [reply lib/aewallet/elixir_wallet.ex]: I have some difficulties understanding you. I'm not using the mnemonic as password of any type. I just typed what the function will return when you call it: an :ok message, the mnemonic itself, the path where the wallet is saved and the type of the created wallet.

Comment (thepiwo) [reply lib/aewallet/elixir_wallet.ex]: "whisper edit clump violin blame few ancient..." is a mnemonic or a password?

Comment (gspasov) [reply lib/aewallet/elixir_wallet.ex]: It's the mnemonic phrase. I'm not returning the password to the user.

Comment (thepiwo) [reply lib/aewallet/elixir_wallet.ex]: I'm sorry, I misunderstood the example and thought it's part of the arguments...
