### PR TITLE
[GH-#94] Added Dialyzer and fixed most of the issues

### LINKED ISSUE #94: add dialyzer and fix eventual issues

### PR DESCRIPTION
**Pull request by gspasov**
resolves #94

### CODE REVIEW

File: lib/aewallet/elixir_wallet.ex [hunk 1]
```diff
@@ -52,13 +52,13 @@ defmodule Aewallet.Wallet do
       {:ok, "whisper edit clump violin blame few ancient casual
       sand trip update spring", "home/desktop/wallet/...", :btc}
   """
-  @spec create_wallet(String.t(), String.t()) :: String.t()
+  @spec create_wallet(String.t(), String.t()) :: tuple()
```
Comment (thepiwo) [inline lib/aewallet/elixir_wallet.ex]: for each of the `tuple()` it would be better to have it described as the actual types. e.g. `{:ok | :error, String.t()}`

Comment (gspasov) [reply lib/aewallet/elixir_wallet.ex]: It never returns :error

Comment (thepiwo) [reply lib/aewallet/elixir_wallet.ex]: it was just an example, adjust the types accordingly to what it actually returns

File: mix.exs [hunk 2]
```diff
@@ -5,7 +5,7 @@ defmodule Aewallet.Mixfile do
     [
       app: :aewallet,
       version: "0.1.0",
-      elixir: "~> 1.5",
+      elixir: "~> 1.6.0",
```
Comment (thepiwo) [inline mix.exs]: specify just `1.6` so it works with 1.6.1 as well

File: lib/aewallet/elixir_wallet.ex (hunk 1 above)
Comment (thepiwo) [reply lib/aewallet/elixir_wallet.ex]: here is still `tuple()`

File: lib/aewallet/elixir_wallet.ex [hunk 3]
```diff
@@ -52,13 +52,13 @@ defmodule Aewallet.Wallet do
...
   def create_wallet(password, path) do
     create_wallet(password, path, "", [])
   end
 
-  @spec create_wallet(String.t(), String.t(), String.t(), wallet_opts()) :: String.t()
-  def create_wallet(password, path, pass_phrase \\ "", opts \\ []) do
+  @spec create_wallet(String.t(), String.t(), String.t(), wallet_opts()) :: tuple()
```
Comment (thepiwo) [inline lib/aewallet/elixir_wallet.ex]: here is still `tuple()`
