### PR TITLE
GH-#77 Added documentation, cleared out some code, fixed the tests and credo

### LINKED ISSUE #77: Document some functions
Some function need documentation

### PR DESCRIPTION
**Pull request by gspasov**
fixes #77

### CODE REVIEW

File: lib/elixir_wallet/key_pair.ex [hunk 1]
```diff
@@ -16,25 +17,50 @@ defmodule KeyPair do
...
+  def generate_master_key(seed_bin, :btc) do
+     build_master_key(:crypto.hmac(:sha512, @bitcoin_key, seed_bin), :btc)
+  end
+  def generate_master_key(seed_bin, :ae) do
+     build_master_key(:crypto.hmac(:sha512, @aeternity_key, seed_bin), :ae)
   end
-  def generate_master_key(seed_bin, :seed, :ae) do
-    generate_master_key(:crypto.hmac(:sha512, @aeternity_key, seed_bin), :ae, :private)
+  def generate_master_key(_, currency) do
+     IO.warn("The cryptocurrency #{currency} is not supported! Check the doc for more info.")
```
Comment (thepiwo) [inline lib/elixir_wallet/key_pair.ex]: maybe throw an exception instead

File: test/public_key_and_address_test.exs [hunk 2]
```diff
@@ -2,61 +2,54 @@ defmodule PublicKeyAndAddressTest do
...
     public_key = master_key |> KeyPair.derive("M/43'/1234/123/10")
 
-    public_key_hex =
-      public_key.key
-      |> KeyPair.compress()
-      |> Base.encode16(case: :lower)
+    public_key_hex = public_key.key |> Base.encode16()
 
-    assert "03c405a99d6131a57a87eea17405e6f3a64f58460b02b2aaccd2b9d019eb0e364a"
+    assert "04C405A99D6131A57A87EEA17405E6F3A64F58460B02B2AACCD2B9D019EB0E364A91A1037E1E2AAD068711AD39672AABD23E76D1F8C40EBA9167907F5FF194A281"
```
Comment (thepiwo) [inline test/public_key_and_address_test.exs]: why has this changed?

Comment (thepiwo) [reply test/public_key_and_address_test.exs]: ah it is uppercase and the prefix changed

Comment (gspasov) [reply test/public_key_and_address_test.exs]: This is changed because it was not correct. It wasn't correct because I checked the "correct" values from [this](https://iancoleman.io/bip39/) website, but it turned out that they make the address there from compressed public keys, but actually it should be done with uncompressed ones. Check [here](https://en.bitcoin.it/wiki/Technical_background_of_version_1_Bitcoin_addresses)

Comment (thepiwo) [reply test/public_key_and_address_test.exs]: thanks!
